In [17]:
from pathlib import Path
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt


#loading initial imputs and outputs 
X= np.load('../data/initial_data/function_6/initial_inputs.npy')
y = np.load('../data/initial_data/function_6/initial_outputs.npy')

#checking shape of data 
print('Inputs Shape:', X.shape)
print('Outputs Shape:', y.shape)

#creating a dataframe 
df=pd.DataFrame(X, columns=['x1', 'x2', 'x3', 'x4', 'x5'])
df['y']=y

#checking DataFrame
df.head(50)

Inputs Shape: (20, 5)
Outputs Shape: (20,)

          x1        x2        x3        x4        x5         y
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882

In [19]:
# --- add new observation for Function 3 ---
new_row = pd.DataFrame([{
    'x1': 0.402,
    'x2': 0.075333,
    'x3': 0.794,
    'x4': 0.99,
    'x5': 0.01,
    'y': -0.6915393
}, {'x1': 0.467333, 'x2': 0.271333, 'x3': 0.467333, 'x4': 0.859333, 'x5': 0.01, 'y': -0.5611604}, {
        'x1': 0.467333,
        'x2': 0.01,
        'x3': 0.663333,
        'x4': 0.663333,
        'x5': 0.01,
        'y': -0.5631527
    },  {
        'x1': 0.532667,
        'x2': 0.01,
        'x3': 0.467333,
        'x4': 0.99,
        'x5': 0.01,
        'y': -1.024728419
    }, {
        'x1': 0.467333,
        'x2': 0.336667,
        'x3': 0.99,
        'x4': 0.663333,
        'x5': 0.01,
        'y': -0.6130133
    }, {
        'x1': 0.402,
        'x2': 0.336667,
        'x3': 0.532667,
        'x4': 0.728667,
        'x5': 0.140667,
        'y': -0.168525512
    }, {
    'x1': 0.206,
    'x2': 0.336667,
    'x3': 0.336667,
    'x4': 0.728667,
    'x5': 0.206,
    'y': -0.653878
}])

# append to df
df = pd.concat([df, new_row], ignore_index=True)

# rebuild X and y from the *updated* df
X = df[['x1', 'x2', 'x3', 'x4', 'x5']].to_numpy()
y = df['y'].to_numpy()

# sanity check
print("len(df):", len(df))
print("Inputs Shape:", X.shape)
print("Outputs Shape:", y.shape)
print(df.tail())

# Check
#checking DataFrame
df.head(50)

len(df): 27
Inputs Shape: (27, 5)
Outputs Shape: (27,)
          x1        x2        x3        x4        x5         y
22  0.467333  0.010000  0.663333  0.663333  0.010000 -0.563153
23  0.532667  0.010000  0.467333  0.990000  0.010000 -1.024728
24  0.467333  0.336667  0.990000  0.663333  0.010000 -0.613013
25  0.402000  0.336667  0.532667  0.728667  0.140667 -0.168526
26  0.206000  0.336667  0.336667  0.728667  0.206000 -0.653878

          x1        x2        x3        x4        x5         y
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.402000  0.075333  0.794000  0.990000  0.010000 -0.691539
21  0.467333  0.271333  0.467333  0.859333  0.010000 -0.561160
22  0.467333  0.010000  0.663333  0.663333  0.010000 -0.563153
23  0.532667  0.010000  0.467333  0.990000  0.010000 -1.024728
24  0.467333  0.336667  0.990000  0.663333  0.010000 -0.613013
25  0.402000  0.336667  0.532667  0.728667  0.140667 -0.168526
26  0.206000  0.336667  0.336667  0.728667  0.206000 -0.653878

In [21]:
#setting parameters and making  grid 
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, WhiteKernel, ConstantKernel as C


#hyperparamters for GP surrogate model and acqusition function 
rbf_lengthscale = 0.5
noise_assumption = 0.1
xi = 0.03

# grid
#g = np.linspace(0.01, 0.99, 16)
#x1g, x2g, x3g, x4g, x5g = np.meshgrid(g, g, g, g, g, indexing='ij')
#X_grid = np.column_stack([x1g.ravel(), x2g.ravel(), x3g.ravel(), x4g.ravel(), x5g.ravel()])
#print(X_grid.shape)

# number of random candidate points
n_candidates = 5000

# sample uniformly from [0, 1]^5
X_candidates = np.random.rand(n_candidates, 5)

In [23]:
#fit GP to current data 
kernel = (C(1.0, (1e-2, 1e2)) * RBF(length_scale=[0.5, 0.5, 0.5, 0.5, 0.5], length_scale_bounds=(0.05, 2))
    + WhiteKernel(noise_level=0.1 , noise_level_bounds=(1e-10, 0.5)))
gp = GaussianProcessRegressor(kernel=kernel, normalize_y=True, n_restarts_optimizer=20, random_state=0)
gp.fit(X, y)

GaussianProcessRegressor(kernel=1**2 * RBF(length_scale=[0.5, 0.5, 0.5, 0.5, 0.5]) + WhiteKernel(noise_level=0.1),
                         n_restarts_optimizer=20, normalize_y=True,
                         random_state=0)

In [25]:
from scipy.stats import norm
import numpy as np

def expected_improvement(mu, sigma, y_best, xi=0.02):
    sigma = np.maximum(sigma, 1e-12)
    imp = mu - y_best - xi
    Z = imp / sigma
    return imp * norm.cdf(Z) + sigma * norm.pdf(Z)

# predict GP on candidate set
#mu, std = gp.predict(X_grid, return_std=True)
mu, std = gp.predict(X_candidates, return_std=True)

# best observed so far (maximization)
y_best = float(np.max(y))

# compute EI and select next point
ei = expected_improvement(mu, std, y_best, xi=xi)  
#ix = int(np.argmax(ei))
#x_next = X_grid[ix]
ix = int(np.argmax(ei))
x_next = X_candidates[ix]

print(f"x_next = ({x_next[0]:.6f}, {x_next[1]:.6f},{x_next[2]:.6f},{x_next[3]:.6f},{x_next[4]:.6f} ) ")

x_next = (0.346309, 0.370462,0.716183,0.799242,0.300238 )

In [27]:
#x_next check 
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import euclidean_distances

model        = gp
X_candidates = np.array(X_grid)   # shape (n_candidates, n_dims)
acq_values   = np.array(ei)   # shape (n_candidates,)
x_next       = np.array(x_next)   # shape (n_dims,)
y_best       = y_best
X_sampled    = np.array(X)   # all evaluated X so far


def _percentile_of_score(values, score):
    """Simple percentile rank: percentage of values <= score."""
    values = np.asarray(values).ravel()
    return float(100.0 * (np.sum(values <= score) / max(len(values), 1)))

def _first_length_scale_from_kernel(kernel):
    """Extract effective GP length-scale (handles RBF, Matern, etc.)."""
    if hasattr(kernel, "length_scale"):
        ls = getattr(kernel, "length_scale")
        try:
            ls = float(np.mean(ls))
        except Exception:
            ls = float(ls)
        return ls
    for attr in ("k1", "k2"):
        if hasattr(kernel, attr):
            ls = _first_length_scale_from_kernel(getattr(kernel, attr))
            if ls is not None:
                return ls
    return None

def _nearest_dist_over_ell(x_next, X_sampled, ell):
    """Compute distance from x_next to nearest sampled point ÷ ell."""
    x_next = np.asarray(x_next, dtype=float).reshape(1, -1)
    X_sampled = np.asarray(X_sampled, dtype=float)
    if X_sampled.size == 0:
        return np.nan
    dists = euclidean_distances(x_next, X_sampled).ravel()
    d_min = float(np.min(dists))
    if (ell is None) or (ell <= 0):
        return np.nan
    return d_min / ell

def _classify_strategy(sig_pct):
    """Assign strategy label from σ percentile (bounded exploration)."""
    if sig_pct <= 40:
        return "Exploit"
    elif sig_pct <= 75:
        return "Balanced"
    elif sig_pct <= 85:
        return "Explore"
    else:
        return "Too exploratory"

def sanity_check_table(model, X_candidates, acq_values, x_next, y_best, X_sampled):
    """
    Builds a 1-row DataFrame with:
      μ_raw (raw), σ_pct (scaled %), dist_over_ℓ_raw (raw), acq_pct (scaled %), Strategy
    """

    # Ensure arrays are the correct shape
    X_candidates = np.asarray(X_candidates, dtype=float)
    acq_values = np.asarray(acq_values, dtype=float).ravel()
    x_next = np.asarray(x_next, dtype=float).ravel()

    # 1) Predict μ, σ for all candidates (for percentiles) and for x_next
    mu_all, sigma_all = model.predict(X_candidates, return_std=True)
    mu_xn, sigma_xn = model.predict(x_next.reshape(1, -1), return_std=True)
    mu_xn = float(mu_xn.ravel()[0])
    sigma_xn = float(sigma_xn.ravel()[0])

    # 2) Percentiles for σ and acquisition
    sig_pct = _percentile_of_score(sigma_all, sigma_xn)

    # Find acquisition value at x_next by matching to nearest candidate
    idx_closest = np.argmin(np.sum((X_candidates - x_next.reshape(1, -1))**2, axis=1))
    acq_xn = float(acq_values[idx_closest])
    acq_pct = _percentile_of_score(acq_values, acq_xn)

    # 3) Distance / ell
    ell = None
    if hasattr(model, "kernel_"):
        ell = _first_length_scale_from_kernel(model.kernel_)
    dist_over_ell = _nearest_dist_over_ell(x_next, X_sampled, ell)

    # 4) Strategy classification
    strategy = _classify_strategy(sig_pct)

    # 5) Build the 1-row DataFrame (rounded for readability)
    data = {
        "μ_raw (raw)":            np.round(mu_xn, 3),
        "σ_pct (scaled %)":       int(np.round(sig_pct)),
        "dist_over_ℓ_raw (raw)":  np.round(dist_over_ell, 3) if np.isfinite(dist_over_ell) else np.nan,
        "acq_pct (scaled %)":     int(np.round(acq_pct)),
        "Strategy":               strategy
    }

    return pd.DataFrame([data])
   

result_df = sanity_check_table(model, X_candidates, acq_values, x_next, y_best, X_sampled)
result_df

NameError: name 'X_grid' is not defined