In [1]:
from pathlib import Path
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt


#loading initial imputs and outputs 
X= np.load('../data/initial_data/function_7/initial_inputs.npy')
y = np.load('../data/initial_data/function_7/initial_outputs.npy')

#checking shape of data 
print('Inputs Shape:', X.shape)
print('Outputs Shape:', y.shape)

#creating a dataframe 
df=pd.DataFrame(X, columns=['x1', 'x2', 'x3', 'x4', 'x5', 'x6'])
df['y']=y

#checking DataFrame
df.head(50)

Inputs Shape: (30, 6)
Outputs Shape: (30,)

          x1        x2        x3        x4        x5        x6         y
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411

In [2]:
# --- add new observation for Function 3 ---
new_row = pd.DataFrame([{
    'x1': 0.186649,
    'x2': 0.391799,
    'x3': 0.410934,
    'x4': 0.056437,
    'x5': 0.23117,
    'x6': 0.922065,
    'y': 0.928735964
},{
        'x1': 0.017556,
        'x2': 0.870861,
        'x3': 0.131613,
        'x4': 0.009644,
        'x5': 0.176664,
        'x6': 0.54813,
        'y': 0.123117302
    },{
    'x1': 0.113221,
    'x2': 0.078252,
    'x3': 0.093951,
    'x4': 0.320307,
    'x5': 0.386583,
    'x6': 0.850604,
    'y':  1.698769338
},  {
        'x1': 0.029561,
        'x2': 0.031032,
        'x3': 0.025565,
        'x4': 0.796718,
        'x5': 0.062116,
        'x6': 0.704649,
        'y': 0.057969698778201
    }, {
        'x1': 0.032429,
        'x2': 0.154432,
        'x3': 0.152698,
        'x4': 0.007213,
        'x5': 0.231466,
        'x6': 0.871125,
        'y': 0.747379595
    }, {
        'x1': 0.171755,
        'x2': 0.179696,
        'x3': 0.162485,
        'x4': 0.210675,
        'x5': 0.479263,
        'x6': 0.90479,
        'y':  1.005516527
    }, {
    "x1": 0.035236,
    "x2": 0.058013,
    "x3": 0.100413,
    "x4": 0.354105,
    "x5": 0.309592,
    "x6": 0.854973,
    "y":  1.675356406
}])
# append to df
df = pd.concat([df, new_row], ignore_index=True)

# rebuild X and y from the *updated* df
X = df[['x1', 'x2', 'x3', 'x4', 'x5', 'x6']].to_numpy()
y = df['y'].to_numpy()

# sanity check
print("len(df):", len(df))
print("Inputs Shape:", X.shape)
print("Outputs Shape:", y.shape)
print(df.tail())

# Check
#checking DataFrame
df.head(50)

len(df): 37
Inputs Shape: (37, 6)
Outputs Shape: (37,)
          x1        x2        x3        x4        x5        x6         y
32  0.113221  0.078252  0.093951  0.320307  0.386583  0.850604  1.698769
33  0.029561  0.031032  0.025565  0.796718  0.062116  0.704649  0.057970
34  0.032429  0.154432  0.152698  0.007213  0.231466  0.871125  0.747380
35  0.171755  0.179696  0.162485  0.210675  0.479263  0.904790  1.005517
36  0.035236  0.058013  0.100413  0.354105  0.309592  0.854973  1.675356

          x1        x2        x3        x4        x5        x6         y
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411
30  0.186649  0.391799  0.410934  0.056437  0.231170  0.922065  0.928736
31  0.017556  0.870861  0.131613  0.009644  0.176664  0.548130  0.123117
32  0.113221  0.078252  0.093951  0.320307  0.386583  0.850604  1.698769
33  0.029561  0.031032  0.025565  0.796718  0.062116  0.704649  0.057970
34  0.032429  0.154432  0.152698  0.007213  0.231466  0.871125  0.747380
35  0.171755  0.179696  0.162485  0.210675  0.479263  0.904790  1.005517
36  0.035236  0.058013  0.100413  0.354105  0.309592  0.854973  1.675356

In [3]:
#setting parameters and making grid 
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, WhiteKernel, ConstantKernel as C
from scipy.stats import norm

#hyperparamters for GP surrogate model and acqusition function 
matern_lengthscale = 0.2
nu = 1.5 
noise_assumption = 0.2
beta = 3

n_candidates = 5000  
# sample uniformly in [0, 1]^6
X_candidates = np.random.rand(n_candidates, 6)

In [4]:
#fit the gp to the current data 
kernel = (C(1.0, (1e-2, 1e2)) * Matern(length_scale= 0.2, length_scale_bounds=(0.05, 1), nu=1.5) 
    + WhiteKernel(noise_level=0.2, noise_level_bounds=(1e-8, 1)))
gp = GaussianProcessRegressor(kernel=kernel, normalize_y=True, n_restarts_optimizer=8, random_state=0)
gp.fit(X, y)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/gaussian_process/kernels.py:442: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-08. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

GaussianProcessRegressor(kernel=1**2 * Matern(length_scale=0.2, nu=1.5) + WhiteKernel(noise_level=0.2),
                         n_restarts_optimizer=8, normalize_y=True,
                         random_state=0)

In [5]:
#compute acquisition UCB on the grid 
#posterior mean and std 
from scipy.stats import norm
import numpy as np

mu, std = gp.predict(X_candidates, return_std = True)
#std = np.maximum(std, 1e-12)

#UCB acquistion 
ucb= mu + beta * std

In [8]:
#choose next query point 
# sample random candidate points
n_candidates = 5000
X_candidates = np.random.rand(n_candidates, 6)

# predict mean + std at candidate points
mu, sigma = gp.predict(X_candidates, return_std=True)

# compute UCB
ucb = mu + beta * sigma

# choose best candidate
ix = np.argmax(ucb)
x_next = X_candidates[ix]

print(f"x_next = ({x_next[0]:.6f}, {x_next[1]:.6f}, {x_next[2]:.6f}, "
      f"{x_next[3]:.6f}, {x_next[4]:.6f}, {x_next[5]:.6f})")

x_next = (0.059410, 0.047540, 0.388538, 0.409099, 0.413585, 0.762862)

In [10]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import euclidean_distances

#create acqusition values 
acq_values = []
for x in X_candidates:
    mu, sigma = model.predict(x.reshape(1, -1), return_std=True)
    ucb = mu + beta * sigma
    acq_values.append(ucb)

# values to imput 
acq_values = np.array(acq_values)
y_best   = float(np.max(y))
model    = gp
X_sampled = np.array(X)  # your already-evaluated points
ix_next = int(np.argmax(acq_values))
x_next  = X_candidates[ix_next]

def _percentile_of_score(values, score):
    """Simple percentile rank: percentage of values <= score."""
    values = np.asarray(values).ravel()
    return float(100.0 * (np.sum(values <= score) / max(len(values), 1)))

def _first_length_scale_from_kernel(kernel):
    """Extract effective GP length-scale (handles RBF, Matern, etc.)."""
    if hasattr(kernel, "length_scale"):
        ls = getattr(kernel, "length_scale")
        try:
            ls = float(np.mean(ls))
        except Exception:
            ls = float(ls)
        return ls
    for attr in ("k1", "k2"):
        if hasattr(kernel, attr):
            ls = _first_length_scale_from_kernel(getattr(kernel, attr))
            if ls is not None:
                return ls
    return None

def _nearest_dist_over_ell(x_next, X_sampled, ell):
    """Compute distance from x_next to nearest sampled point ÷ ell."""
    x_next = np.asarray(x_next, dtype=float).reshape(1, -1)
    X_sampled = np.asarray(X_sampled, dtype=float)
    if X_sampled.size == 0:
        return np.nan
    dists = euclidean_distances(x_next, X_sampled).ravel()
    d_min = float(np.min(dists))
    if (ell is None) or (ell <= 0):
        return np.nan
    return d_min / ell

def _classify_strategy(sig_pct):
    """Assign strategy label from σ percentile (bounded exploration)."""
    if sig_pct <= 40:
        return "Exploit"
    elif sig_pct <= 75:
        return "Balanced"
    elif sig_pct <= 85:
        return "Explore"
    else:
        return "Too exploratory"

def sanity_check_table(model, X_candidates, acq_values, x_next, y_best, X_sampled):
    """
    Builds a 1-row DataFrame with:
      μ_raw (raw), σ_pct (scaled %), dist_over_ℓ_raw (raw), acq_pct (scaled %), Strategy
    """

    # Ensure arrays are the correct shape
    X_candidates = np.asarray(X_candidates, dtype=float)
    acq_values = np.asarray(acq_values, dtype=float).ravel()
    x_next = np.asarray(x_next, dtype=float).ravel()

    # 1) Predict μ, σ for all candidates (for percentiles) and for x_next
    mu_all, sigma_all = model.predict(X_candidates, return_std=True)
    mu_xn, sigma_xn = model.predict(x_next.reshape(1, -1), return_std=True)
    mu_xn = float(mu_xn.ravel()[0])
    sigma_xn = float(sigma_xn.ravel()[0])

    # 2) Percentiles for σ and acquisition
    sig_pct = _percentile_of_score(sigma_all, sigma_xn)

    # Find acquisition value at x_next by matching to nearest candidate
    idx_closest = np.argmin(np.sum((X_candidates - x_next.reshape(1, -1))**2, axis=1))
    acq_xn = float(acq_values[idx_closest])
    acq_pct = _percentile_of_score(acq_values, acq_xn)

    # 3) Distance / ell
    ell = None
    if hasattr(model, "kernel_"):
        ell = _first_length_scale_from_kernel(model.kernel_)
    dist_over_ell = _nearest_dist_over_ell(x_next, X_sampled, ell)

    # 4) Strategy classification
    strategy = _classify_strategy(sig_pct)

    # 5) Build the 1-row DataFrame (rounded for readability)
    data = {
        "μ_raw (raw)":            np.round(mu_xn, 3),
        "σ_pct (scaled %)":       int(np.round(sig_pct)),
        "dist_over_ℓ_raw (raw)":  np.round(dist_over_ell, 3) if np.isfinite(dist_over_ell) else np.nan,
        "acq_pct (scaled %)":     int(np.round(acq_pct)),
        "Strategy":               strategy
    }

    return pd.DataFrame([data])
   

result_df = sanity_check_table(model, X_candidates, acq_values, x_next, y_best, X_sampled)
result_df

NameError: name 'model' is not defined